/*
 * Welcome to NetBeans...!!!
 */
package traders;

import java.awt.Component;
import java.awt.Container;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.Arrays;
import javax.swing.JRadioButton;

/**
 *
 * @author admin
 */
public class RegisterPane extends javax.swing.JPanel {

    ShoppingGUI mainGUI;
    
    ProfileInformation profileInfo;
    ActionListener rbActionListener;
    
    /**
     * Creates new form RegisterPane
     * @param objMainGUI
     */
    public RegisterPane(ShoppingGUI objMainGUI) {
        initComponents();
        
        this.mainGUI = objMainGUI;                
        this.profileInfo = new ProfileInformation();
        
        // Initialize listener and then add it to the buttons
        initializeRadioButtonActionListener();
        groupRadioButtons();        

        // By default, disable both Register/Sign In panels so that user shall select one radio button
        EnableComponents(pnlRegister, false);
        EnableComponents(pnlLogin, false);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnOptionsGroup = new javax.swing.ButtonGroup();
        pnlContainer = new javax.swing.JPanel();
        pnlWelcome = new javax.swing.JPanel();
        rbRegister = new javax.swing.JRadioButton();
        rbSignIn = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        pnlRegister = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tfRegUserName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        pfRegPassword = new javax.swing.JPasswordField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        pfRegConfirmPwd = new javax.swing.JPasswordField();
        btnRegister = new javax.swing.JButton();
        btnRegReset = new javax.swing.JButton();
        lblPwdStatus = new javax.swing.JLabel();
        pnlLogin = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        pfLoginPwd = new javax.swing.JPasswordField();
        tfLoginUserName = new javax.swing.JTextField();
        btnLoginReset = new javax.swing.JButton();
        btnLogin = new javax.swing.JButton();
        lblLoginEntryStatus = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        pnlWelcome.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        rbRegister.setText("Register");

        rbSignIn.setText("Sign In");

        jLabel7.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 255));
        jLabel7.setText("SalesShore welcomes you...!!!  ");

        javax.swing.GroupLayout pnlWelcomeLayout = new javax.swing.GroupLayout(pnlWelcome);
        pnlWelcome.setLayout(pnlWelcomeLayout);
        pnlWelcomeLayout.setHorizontalGroup(
            pnlWelcomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlWelcomeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(rbRegister)
                .addGap(18, 18, 18)
                .addComponent(rbSignIn)
                .addGap(14, 14, 14))
        );
        pnlWelcomeLayout.setVerticalGroup(
            pnlWelcomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlWelcomeLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(pnlWelcomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbSignIn, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(rbRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(250, 250, 250))
        );

        pnlRegister.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setText("Got something to Trade...");

        jLabel2.setText("Register here and Enjoy trading..!!!");

        tfRegUserName.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel3.setText("Username ");

        jLabel4.setText("Password");

        pfRegPassword.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        pfRegPassword.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                pfRegPasswordInputMethodTextChanged(evt);
            }
        });

        jLabel5.setText("(Min. 8 Chars)");

        jLabel6.setText("Confirm Password");

        pfRegConfirmPwd.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        pfRegConfirmPwd.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                pfRegConfirmPwdInputMethodTextChanged(evt);
            }
        });

        btnRegister.setText("Register");
        btnRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegisterActionPerformed(evt);
            }
        });

        btnRegReset.setText("Reset");
        btnRegReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegResetActionPerformed(evt);
            }
        });

        lblPwdStatus.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout pnlRegisterLayout = new javax.swing.GroupLayout(pnlRegister);
        pnlRegister.setLayout(pnlRegisterLayout);
        pnlRegisterLayout.setHorizontalGroup(
            pnlRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRegisterLayout.createSequentialGroup()
                .addGroup(pnlRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlRegisterLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(pnlRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlRegisterLayout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(tfRegUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlRegisterLayout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(pfRegPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlRegisterLayout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(pfRegConfirmPwd, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlRegisterLayout.createSequentialGroup()
                                .addGroup(pnlRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel1)
                                    .addGroup(pnlRegisterLayout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(jLabel2)))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(pnlRegisterLayout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addComponent(btnRegister)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnRegReset))
                    .addGroup(pnlRegisterLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblPwdStatus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pnlRegisterLayout.setVerticalGroup(
            pnlRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRegisterLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addGap(23, 23, 23)
                .addGroup(pnlRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tfRegUserName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(pfRegPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(pfRegConfirmPwd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblPwdStatus)
                .addGap(13, 13, 13)
                .addGroup(pnlRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRegister)
                    .addComponent(btnRegReset))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pnlLogin.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel9.setText("Already signed up...");

        jLabel10.setText("Log in and happy Trading...!!!");

        jLabel11.setText("Username ");

        jLabel12.setText("Password ");

        pfLoginPwd.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        tfLoginUserName.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        btnLoginReset.setText("Reset ");
        btnLoginReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginResetActionPerformed(evt);
            }
        });

        btnLogin.setText("Log In");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });

        lblLoginEntryStatus.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout pnlLoginLayout = new javax.swing.GroupLayout(pnlLogin);
        pnlLogin.setLayout(pnlLoginLayout);
        pnlLoginLayout.setHorizontalGroup(
            pnlLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLoginLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblLoginEntryStatus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pnlLoginLayout.createSequentialGroup()
                        .addGroup(pnlLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlLoginLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabel10))
                            .addComponent(jLabel9)
                            .addGroup(pnlLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(pnlLoginLayout.createSequentialGroup()
                                    .addComponent(jLabel11)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(tfLoginUserName))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlLoginLayout.createSequentialGroup()
                                    .addComponent(jLabel12)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(pfLoginPwd, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(pnlLoginLayout.createSequentialGroup()
                                    .addComponent(btnLogin)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(btnLoginReset))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pnlLoginLayout.setVerticalGroup(
            pnlLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLoginLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel10)
                .addGap(24, 24, 24)
                .addGroup(pnlLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(tfLoginUserName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(pfLoginPwd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(lblLoginEntryStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 9, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLogin)
                    .addComponent(btnLoginReset))
                .addGap(19, 19, 19))
        );

        javax.swing.GroupLayout pnlContainerLayout = new javax.swing.GroupLayout(pnlContainer);
        pnlContainer.setLayout(pnlContainerLayout);
        pnlContainerLayout.setHorizontalGroup(
            pnlContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlWelcome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlContainerLayout.createSequentialGroup()
                .addComponent(pnlRegister, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        pnlContainerLayout.setVerticalGroup(
            pnlContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlContainerLayout.createSequentialGroup()
                .addComponent(pnlWelcome, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pnlRegister, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlContainer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlContainer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void groupRadioButtons() {
        
        this.btnOptionsGroup.add(rbRegister);
        this.btnOptionsGroup.add(rbSignIn);
        
        this.rbRegister.addActionListener(rbActionListener);
        this.rbSignIn.addActionListener(rbActionListener);
    }
    
    private void initializeRadioButtonActionListener() {
       rbActionListener = (ActionEvent actionEvent) -> {
            JRadioButton aButton = (JRadioButton) actionEvent.getSource();
            
            if (aButton == rbRegister) {
                // Option Register is selected
                this.tfRegUserName.setText("");
                this.pfRegPassword.setText("");
                this.pfRegConfirmPwd.setText("");
                EnableComponents(pnlLogin, false);
                EnableComponents(pnlRegister, true);                
                
            } else if (aButton == rbSignIn) {
                // Option Sign In is selected
                this.tfLoginUserName.setText("");
                this.pfLoginPwd.setText("");
                EnableComponents(pnlRegister, false);
                EnableComponents(pnlLogin, true);
            }
        }; 
    }
    
    // Enables of disables the children of the entire parent container
    private void EnableComponents(Container container, boolean bEnable) {
        Component[] components = container.getComponents();
        for (Component component : components) {
            component.setEnabled(bEnable);
            if (component instanceof Container) {
                EnableComponents((Container)component, bEnable);
            }
        }
    }
    
    private boolean isPasswordCorrect() {
        
        boolean isCorrect = true;
        
        char[] correctPassword = this.pfRegPassword.getPassword();
        char[] enteredPassword = this.pfRegConfirmPwd.getPassword();
        
        if (enteredPassword.length != correctPassword.length) {
            isCorrect = false;
        } else {
            isCorrect = Arrays.equals(enteredPassword, correctPassword);
        }

        //Zero out the password
        Arrays.fill(correctPassword,'0');
        Arrays.fill(enteredPassword, '0');

        return isCorrect;
    }
   
    public void enableLoginPanel() {
        
        this.tfLoginUserName.setText("");
        this.pfLoginPwd.setText("");
        EnableComponents(pnlLogin, true);
    }
    
    private void btnRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisterActionPerformed
        
        if (isPasswordCorrect()) {
            this.lblPwdStatus.setText("Passwords matched");
            profileInfo.setTraderName(this.tfRegUserName.getText());
            profileInfo.setPassword(new String(this.pfRegPassword.getPassword()));
            
            // Call method on the Main GUI class to invoke Remote method on server
            boolean bRetValue = mainGUI.connectToMarket(profileInfo, true);            
            if(bRetValue) {                
                mainGUI.setStatus("Login to continue...");
                EnableComponents(pnlRegister, false);
                EnableComponents(pnlLogin, true);
            }
        } else {
            this.pfRegPassword.setText("");
            this.pfRegConfirmPwd.setText("");
            this.lblPwdStatus.setText("Passwords do not match");
        }
    }//GEN-LAST:event_btnRegisterActionPerformed

    private void btnRegResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegResetActionPerformed
        
        this.tfRegUserName.setText("");
        this.pfRegPassword.setText("");
        this.pfRegConfirmPwd.setText("");
    }//GEN-LAST:event_btnRegResetActionPerformed

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        
        String strUserName = this.tfLoginUserName.getText();
        String strPassWord = new String(this.pfLoginPwd.getPassword());
        if(!"".equals(strUserName) && !"".equals(strPassWord)) {
            profileInfo.setTraderName(strUserName);
            profileInfo.setPassword(strPassWord);
            
            // Call method on the Main GUI class to invoke Remote method on server
            boolean bRetValue = mainGUI.connectToMarket(profileInfo, false);
            if(bRetValue) {
                mainGUI.setStatus("Happy Trading...");
                EnableComponents(pnlRegister, false);
                EnableComponents(pnlLogin, false);                
            }
        } else {
            this.lblLoginEntryStatus.setText("Username/Password can't be empty");
        }
    }//GEN-LAST:event_btnLoginActionPerformed

    private void btnLoginResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginResetActionPerformed
        
        this.tfLoginUserName.setText("");
        this.pfLoginPwd.setText("");
    }//GEN-LAST:event_btnLoginResetActionPerformed

    private void pfRegPasswordInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_pfRegPasswordInputMethodTextChanged
        this.lblPwdStatus.setText("");
    }//GEN-LAST:event_pfRegPasswordInputMethodTextChanged

    private void pfRegConfirmPwdInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_pfRegConfirmPwdInputMethodTextChanged
        this.lblPwdStatus.setText("");
    }//GEN-LAST:event_pfRegConfirmPwdInputMethodTextChanged

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogin;
    private javax.swing.JButton btnLoginReset;
    private javax.swing.ButtonGroup btnOptionsGroup;
    private javax.swing.JButton btnRegReset;
    private javax.swing.JButton btnRegister;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lblLoginEntryStatus;
    private javax.swing.JLabel lblPwdStatus;
    private javax.swing.JPasswordField pfLoginPwd;
    private javax.swing.JPasswordField pfRegConfirmPwd;
    private javax.swing.JPasswordField pfRegPassword;
    private javax.swing.JPanel pnlContainer;
    private javax.swing.JPanel pnlLogin;
    private javax.swing.JPanel pnlRegister;
    private javax.swing.JPanel pnlWelcome;
    private javax.swing.JRadioButton rbRegister;
    private javax.swing.JRadioButton rbSignIn;
    private javax.swing.JTextField tfLoginUserName;
    private javax.swing.JTextField tfRegUserName;
    // End of variables declaration//GEN-END:variables
}
