/*
 * Welcome to NetBeans...!!!
 */
package traders;

/**
 *
 * @author admin
 */
public class SellPane extends javax.swing.JPanel {

    ShoppingGUI mainGUI;
    
    /**
     * Creates new form SellPane
     * @param objMainGUI
     */
    public SellPane(ShoppingGUI objMainGUI) {
        initComponents();
        
        this.mainGUI = objMainGUI;
        AddItemstoSell();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlSellItems = new javax.swing.JPanel();
        lstSellItems = new java.awt.List();
        lblEnterPrice = new javax.swing.JLabel();
        btnSellItem = new javax.swing.JButton();
        tfSellingPrice = new javax.swing.JTextField();

        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        pnlSellItems.setBorder(javax.swing.BorderFactory.createTitledBorder("Sell Items"));

        lblEnterPrice.setText("Enter Selling Price (In SEK) ");

        btnSellItem.setText("Sell Item");
        btnSellItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSellItemActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlSellItemsLayout = new javax.swing.GroupLayout(pnlSellItems);
        pnlSellItems.setLayout(pnlSellItemsLayout);
        pnlSellItemsLayout.setHorizontalGroup(
            pnlSellItemsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lstSellItems, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pnlSellItemsLayout.createSequentialGroup()
                .addComponent(lblEnterPrice)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 223, Short.MAX_VALUE)
                .addComponent(btnSellItem))
        );
        pnlSellItemsLayout.setVerticalGroup(
            pnlSellItemsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSellItemsLayout.createSequentialGroup()
                .addComponent(lstSellItems, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlSellItemsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSellItem)
                    .addComponent(lblEnterPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(144, Short.MAX_VALUE)
                .addComponent(tfSellingPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(120, 120, 120))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(pnlSellItems, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(248, Short.MAX_VALUE)
                .addComponent(tfSellingPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(pnlSellItems, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void AddItemstoSell() {
        
        this.lstSellItems.add("Teak Table");
        this.lstSellItems.add("Cotton Shirt");
        this.lstSellItems.add("Hockey Stick");
        this.lstSellItems.add("Cricket Bat");
        this.lstSellItems.add("Woolen Gloves");
        this.lstSellItems.add("Bluetooth Headset");
        this.lstSellItems.add("Steel plate");
        this.lstSellItems.add("Codrey Jeans pant");
        this.lstSellItems.add("Waterproof Woollen Jacket");
        this.lstSellItems.add("Designer T-Shirt");
        this.lstSellItems.add("Table cloth pair");
    }

    public void removeSoldItemFromList(String strItemName) {
        this.lstSellItems.remove(strItemName);
    }
        
    private void btnSellItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSellItemActionPerformed

        String strItemSelectedForSale = this.lstSellItems.getSelectedItem();

        if(strItemSelectedForSale != null) {
            strItemSelectedForSale = strItemSelectedForSale.trim();
            int nSellingPrice = Integer.parseInt(tfSellingPrice.getText().trim());
            
            mainGUI.placeItemForSale(strItemSelectedForSale, nSellingPrice);
        } else {
            mainGUI.setStatus("Select an item to be sold...");
        }
    }//GEN-LAST:event_btnSellItemActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSellItem;
    private javax.swing.JLabel lblEnterPrice;
    private java.awt.List lstSellItems;
    private javax.swing.JPanel pnlSellItems;
    private javax.swing.JTextField tfSellingPrice;
    // End of variables declaration//GEN-END:variables
}
